# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 2
  selector:

    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: ayushishu/ishuayushiweb
        ports:
        - containerPort: 80
          protocol: TCP
  strategy:
    canary:
      steps:
      - setWeight: 10
        pause:
          duration: 30s
      - setWeight: 20
        pause:
          duration: 30s
      - setWeight: 30
        pause:
          duration: 30s
      - setWeight: 100

---
# Service 
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  selector:
    app: myapp
  ports:
  - port: 3000
    targetPort: 80
    protocol: TCP
